package dev.camada.snapshot;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import dev.camada.Fixtures;
import dev.camada.Json;
import dev.camada.events.Builder;
import dev.camada.events.Builder.RequestInfo;
import dev.camada.snapshot.Matcher.MatchInput;
import dev.camada.snapshot.Matcher.MatchResult;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;

/**
 * Golden conformance: fixtures generated by edge-analyst/scripts/gen-fixtures.mjs, with expected
 * outputs computed by running the reference implementation (src/blocklist.js) itself. A failure
 * here means the port drifted from the format owner — fix the port, never the fixture. This is the
 * Java twin of camada-core/test/conformance.test.ts and camada-python's test_conformance.py, case
 * for case: every fixture case is one dynamic test.
 */
class ConformanceTest {
  static final Map<String, Object> CASES = Fixtures.readMeta("blk3/cases.json");
  static final Map<String, Object> CASES5 =
      Json.asMap(Fixtures.readMeta("blk5/cases.json").get("v5"));
  static final Map<String, Object> HDRS_FX = Fixtures.readMeta("blk3/hdrs.json");

  static Matcher matcher(String name, String d) {
    return new Matcher(
        Parser.parse(
            Fixtures.readBin(d + "/" + name + ".bin"),
            Fixtures.readMeta(d + "/" + name + ".meta.json")));
  }

  static Matcher matcher(String name) {
    return matcher(name, "blk3");
  }

  @SuppressWarnings("unchecked")
  static List<Map<String, Object>> cases(Map<String, Object> root, String... keys) {
    Object v = root;
    for (String k : keys) {
      v = Json.asMap(v).get(k);
    }
    return (List<Map<String, Object>>) (List<?>) v;
  }

  static Map<String, Object> input(Map<String, Object> c) {
    return Json.asMap(c.get("input"));
  }

  static Map<String, Object> expect(Map<String, Object> c) {
    return Json.asMap(c.get("expect"));
  }

  /**
   * A v5 case's `headers` is a map with already lower-cased keys — the request as the tap sees it.
   * It becomes the header(name) getter §D3 defines, exactly as the reference harness does.
   */
  static MatchInput asInput(Map<String, Object> c) {
    return asInput(input(c), true);
  }

  static MatchInput asInput(Map<String, Object> i, boolean withHeaders) {
    Map<String, Object> headers = Json.asMap(i.get("headers"));
    Object asn = i.get("asn");
    return new MatchInput(
        (String) i.get("ip"),
        asn instanceof Number n ? n.longValue() : null,
        (String) i.get("country"),
        (String) i.get("tlsx"),
        (String) i.get("path"),
        (String) i.get("ua"),
        headers != null && withHeaders ? n -> (String) headers.get(n) : null);
  }

  static Map<String, Object> outcome(MatchResult r) {
    // the reference reports "nothing matched" as reason null; the port leaves it null too
    Map<String, Object> m = new LinkedHashMap<>();
    m.put("block", r.block());
    m.put("challenge", r.challenge());
    m.put("allowed", r.allowed());
    m.put("reason", r.reason());
    return m;
  }

  static Map<String, Object> outcome5(MatchResult r) {
    Map<String, Object> m = outcome(r);
    m.put("warn", r.warn());
    m.put("action", r.action());
    m.put("rule", r.rule());
    return m;
  }

  static String label(Map<String, Object> c) {
    return Json.stringify(c.get("input"));
  }

  static Stream<DynamicTest> perCase(
      List<Map<String, Object>> cases, java.util.function.Consumer<Map<String, Object>> check) {
    return cases.stream().map(c -> DynamicTest.dynamicTest(label(c), () -> check.accept(c)));
  }

  @Nested
  class V3V4 {
    @TestFactory
    Stream<DynamicTest> v3Basic() {
      Matcher m = matcher("v3-basic");
      return perCase(
          cases(CASES, "v3", "basic"),
          c -> assertEquals(expect(c), outcome(m.match(asInput(c))), label(c)));
    }

    @TestFactory
    Stream<DynamicTest> v3Empty() {
      Matcher m = matcher("v3-empty");
      return perCase(
          cases(CASES, "v3", "empty"),
          c -> assertEquals(expect(c), outcome(m.match(asInput(c))), label(c)));
    }

    @TestFactory
    Stream<DynamicTest> v4Basic() {
      Matcher m = matcher("v4-basic");
      return perCase(
          cases(CASES, "v4", "basic"),
          c -> assertEquals(expect(c), outcome(m.match(asInput(c))), label(c)));
    }

    @TestFactory
    Stream<DynamicTest> v4Empty() {
      Matcher m = matcher("v4-empty");
      return perCase(
          cases(CASES, "v4", "empty"),
          c -> assertEquals(expect(c), outcome(m.match(asInput(c))), label(c)));
    }
  }

  @Nested
  class V4Outcomes {
    @Test
    void neverTwoOutcomeFlags() {
      Matcher m = matcher("v4-basic");
      List<Map<String, Object>> all = new ArrayList<>(cases(CASES, "v4", "basic"));
      all.addAll(cases(CASES, "v4", "empty"));
      for (Map<String, Object> c : all) {
        MatchResult r = m.match(asInput(c));
        assertTrue(
            (r.allowed() ? 1 : 0) + (r.block() ? 1 : 0) + (r.challenge() ? 1 : 0) <= 1, label(c));
      }
    }

    @Test
    void v3ContainerCannotExpressAllowOrChallenge() {
      Matcher v3 = matcher("v3-basic");
      List<Map<String, Object>> v4c = cases(CASES, "v4", "basic");
      List<Map<String, Object>> v3c = cases(CASES, "v3", "basic");
      assertEquals(v4c.size(), v3c.size());
      int diverged = 0;
      for (int k = 0; k < v4c.size(); k++) {
        if (!expect(v4c.get(k)).equals(expect(v3c.get(k)))) {
          diverged++;
          assertEquals(
              expect(v3c.get(k)), outcome(v3.match(asInput(v4c.get(k)))), label(v4c.get(k)));
        }
      }
      assertTrue(diverged > 0); // the fixtures must actually exercise the new sections
    }
  }

  @Nested
  class V5 {
    @TestFactory
    Stream<DynamicTest> rules() {
      Matcher m = matcher("v5-rules", "blk5");
      return perCase(
          cases(CASES5, "rules"),
          c -> assertEquals(expect(c), outcome5(m.match(asInput(c))), label(c)));
    }

    @TestFactory
    Stream<DynamicTest> empty() {
      Matcher m = matcher("v5-empty", "blk5");
      return perCase(
          cases(CASES5, "empty"),
          c -> assertEquals(expect(c), outcome5(m.match(asInput(c))), label(c)));
    }

    @Test
    void neverTwoOutcomeFlags() {
      Matcher m = matcher("v5-rules", "blk5");
      List<Map<String, Object>> all = new ArrayList<>(cases(CASES5, "rules"));
      all.addAll(cases(CASES5, "empty"));
      for (Map<String, Object> c : all) {
        MatchResult r = m.match(asInput(c));
        int flags =
            (r.allowed() ? 1 : 0)
                + (r.block() ? 1 : 0)
                + (r.challenge() ? 1 : 0)
                + (r.warn() ? 1 : 0);
        assertTrue(flags <= 1, label(c));
      }
    }

    @Test
    void namesTheRuleOnlyWhenARuleDecided() {
      Matcher m = matcher("v5-rules", "blk5");
      for (Map<String, Object> c : cases(CASES5, "rules")) {
        MatchResult r = m.match(asInput(c));
        if ("rule".equals(r.reason())) {
          assertNotNull(r.rule(), label(c));
          assertNotNull(r.action(), label(c));
        } else {
          assertNull(r.rule(), label(c));
          assertNull(r.action(), label(c));
        }
      }
    }

    @Test
    void rulesOverruleTheSidesAV4ContainerCanOnlyRead() {
      Matcher v4 = matcher("v4-basic");
      Matcher rules = matcher("v5-rules", "blk5");
      int diverged = 0;
      for (Map<String, Object> c : cases(CASES5, "rules")) {
        if (!outcome(v4.match(asInput(c))).equals(outcome(rules.match(asInput(c))))) {
          diverged++;
          assertEquals("rule", expect(c).get("reason"), label(c));
        }
      }
      assertTrue(diverged > 0);
    }

    @Test
    void headerCasesDecideThroughTheGetterAlone() {
      Matcher m = matcher("v5-rules", "blk5");
      int headerCases = 0;
      for (Map<String, Object> c : cases(CASES5, "rules")) {
        if (input(c).get("headers") == null) {
          continue;
        }
        headerCases++;
        assertEquals(expect(c), outcome5(m.match(asInput(c))), label(c));
        // no getter: a header condition can never fire (fail open)
        MatchResult blind = m.match(asInput(input(c), false));
        if ("rule".equals(expect(c).get("reason"))) {
          assertNotEquals(expect(c).get("rule"), blind.rule(), label(c));
        } else {
          assertEquals(expect(c).get("reason"), blind.reason(), label(c));
        }
      }
      assertTrue(headerCases > 0);
    }
  }

  @Test
  void interleavedMatchersKeepStateApart() {
    Matcher a = matcher("v4-basic");
    Matcher b = matcher("v4-empty");
    for (int k = 0; k < 20; k++) {
      assertEquals("ip6", a.match(MatchInput.ip("2001:db8::1")).reason());
      assertFalse(b.match(MatchInput.ip("2001:db8::1")).block());
      assertFalse(a.match(MatchInput.ip("2001:db8::2")).block());
    }
  }

  @Nested
  class HdrsBitmask {
    @Test
    void pinsTheExactHeaderOrder() {
      assertEquals(HDRS_FX.get("hdrs"), Builder.HDRS);
    }

    @TestFactory
    Stream<DynamicTest> hmVectors() {
      return cases(HDRS_FX, "cases").stream()
          .map(
              c -> {
                @SuppressWarnings("unchecked")
                List<String> names = (List<String>) (List<?>) c.get("names");
                return DynamicTest.dynamicTest(
                    String.join("+", names),
                    () -> {
                      List<Map.Entry<String, String>> headers = new ArrayList<>();
                      for (String n : names) {
                        headers.add(new AbstractMap.SimpleEntry<>(n, "v"));
                      }
                      Map<String, Object> ev =
                          Builder.build(
                              new RequestInfo("GET", "x.test", "/", "", headers, "1.2.3.4", null),
                              "sdk-java",
                              "r",
                              null,
                              false,
                              null);
                      assertEquals(c.get("hm"), ev.get("hm"));
                    });
              });
    }
  }
}
