#!/usr/bin/env sh
# Re-vendors @camada/browser's auto build into src/main/resources/dev/camada/ (b.js byte for byte,
# plus beacon.properties with its version and sha256), so the jar serves /_cam/b.js with no
# runtime file read. BeaconJsTest fails until the two agree.
#
# Usage: scripts/sync-beacon.sh [path/to/camada-browser]   (defaults to the sibling checkout)
# Run `npm run build` in camada-browser first.
set -eu
root="$(cd "$(dirname "$0")/.." && pwd)"
browser="${1:-$root/../camada-browser}"
src="$browser/dist/auto.global.js"
out="$root/src/main/resources/dev/camada"
[ -f "$src" ] || { echo "beacon build missing: $src (run npm run build in camada-browser)" >&2; exit 1; }
version="$(sed -n 's/^  "version": "\([^"]*\)",$/\1/p' "$browser/package.json" | head -1)"
[ -n "$version" ] || { echo "no version in $browser/package.json" >&2; exit 1; }
if command -v sha256sum >/dev/null 2>&1; then sha="$(sha256sum "$src" | cut -d' ' -f1)"; else sha="$(shasum -a 256 "$src" | cut -d' ' -f1)"; fi
mkdir -p "$out"
cp "$src" "$out/b.js"
printf '# GENERATED by scripts/sync-beacon.sh - do not edit. BeaconJsTest pins b.js to the sibling build.\nversion=%s\nsha256=%s\n' "$version" "$sha" > "$out/beacon.properties"
echo "b.js: @camada/browser/$version, $(wc -c < "$src" | tr -d ' ') bytes, sha256 $sha"
